#include "p16f84a.inc"
 __CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _CP_OFF
COUNT1  EQU 0x10
COUNT2  EQU 0x11
COUNT3  EQU 0x12
    ORG 0x00
    GOTO    MAIN
    ORG 0x04
    RETFIE
SETUP
    BSF     STATUS, RP0
    CLRF    TRISB
    BCF     STATUS, RP0
    CLRF    PORTB
    RETURN
MAIN
    CALL    SETUP
LOOP
    BSF     PORTB, 0
    CALL    DELAY
    BCF     PORTB, 0
    CALL    DELAY
    GOTO    LOOP
DELAY
    MOVLW   0xFF
    MOVWF   COUNT1
LOOP1
    MOVLW   0xFF
    MOVWF   COUNT2
LOOP2
    MOVLW   0xFF
    MOVWF   COUNT3
LOOP3
    DECFSZ  COUNT3, F
    GOTO    LOOP3
    DECFSZ  COUNT2, F
    GOTO    LOOP2
    DECFSZ  COUNT1, F
    GOTO    LOOP1
    RETURN
END